{
 "title": "Solar",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Solar Position",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "aelogs",
     "rawSql": "select altitude as \"Solar Altitude\",datetime from solar.sun_position where $__timeFilter(datetime) "
    },
    {
     "dataset": "aelogs",
     "rawSql": "select azimuth as \"Solar Azimuth\",datetime from solar.sun_position where $__timeFilter(datetime) "
    },
    {
     "dataset": "aelogs",
     "rawSql": "select value_float AS \"Panel Voltage\", datetime FROM solar.renogy20 WHERE $__timeFilter(datetime) AND topic = \"kili/sagehouse/solar/renogy20/solar_panel_voltage\" "
    }
   ]
  },
  {
   "title": "Voltage Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "aelogs",
     "rawSql": "select value_float AS \"Panel Voltage\", datetime FROM solar.renogy20 WHERE $__timeFilter(datetime) AND topic = \"kili/sagehouse/solar/renogy20/solar_panel_voltage\" "
    },
    {
     "dataset": "aelogs",
     "rawSql": "select value_float AS \"Battery Voltage\", datetime FROM solar.renogy20 WHERE $__timeFilter(datetime) AND topic = \"kili/sagehouse/solar/renogy20/battery_voltage\" "
    },
    {
     "dataset": "aelogs",
     "rawSql": "select value_float AS \"Charging Current\", datetime FROM solar.renogy20 WHERE $__timeFilter(datetime) AND topic = \"kili/sagehouse/solar/renogy20/battery_charging_amps\" "
    }
   ]
  },
  {
   "title": "Current Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "dataset": "aelogs",
     "rawSql": "select value_float as \"Charging Current\", datetime FROM solar.renogy20 WHERE topic = \"kili/sagehouse/solar/renogy20/battery_charging_amps\""
    },
    {
     "dataset": "aelogs",
     "rawSql": "select value_float as \"Load Current\", datetime FROM solar.renogy20 WHERE topic = \"kili/sagehouse/solar/renogy20/load_amps\""
    },
    {
     "dataset": "aelogs",
     "rawSql": "select value_float as \"Battery Voltage\", datetime FROM solar.renogy20 WHERE topic = \"kili/sagehouse/solar/renogy20/battery_voltage\""
    }
   ]
  },
  {
   "title": "Solar Temps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "dataset": "aelogs",
     "rawSql": "select value_float as \"Battery Temperature\", datetime FROM solar.renogy20 WHERE $__timeFilter(datetime) AND topic = \"kili/sagehouse/solar/renogy20/battery_temperatureF\""
    },
    {
     "dataset": "aelogs",
     "rawSql": "select value_float as \"Controller Temperature\", datetime FROM solar.renogy20 WHERE $__timeFilter(datetime) AND topic = \"kili/sagehouse/solar/renogy20/controller_temperatureF\""
    },
    {
     "dataset": "aelogs",
     "rawSql": "select value_float as \"Battery Voltage\", datetime FROM solar.renogy20 WHERE $__timeFilter(datetime) AND topic = \"kili/sagehouse/solar/renogy20/battery_voltage\""
    },
    {
     "dataset": "aelogs",
     "rawSql": "select value_float as \"Board Temperature\", datetime FROM solar.renogy20 WHERE $__timeFilter(datetime) AND topic = \"kili/sagehouse/solar/renogy20/board_temperatureF\""
    }
   ]
  },
  {
   "title": "Panel Potential",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "get",
     "keyName": "kili:sagehouse:renogy20:solar_panel_voltage:value",
     "type": "command"
    }
   ]
  },
  {
   "title": "Panel Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "get",
     "keyName": "kili:sagehouse:renogy20:solar_panel_watts:value",
     "type": "command"
    }
   ]
  },
  {
   "title": "Battery Potential",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "get",
     "keyName": "kili:sagehouse:renogy20:battery_voltage:value",
     "type": "command"
    }
   ]
  },
  {
   "title": "Load Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "get",
     "keyName": "kili:sagehouse:renogy20:load_watts:value",
     "type": "command"
    }
   ]
  }
 ]
}